services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: true
  allowed_users:
      - vikrant.chaudhary@physik.hu-berlin.de
      - chaudhary@tmm.tu-darmstadt.de
north:
  enable: true
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  tools:
    include:
      - jupyter
    options:
      jupyter:
        short_description: A JupyterLab container with pre-installed NOMAD plugins.
        image: ghcr.io/16-vikrant/nomad-oasis-tmm/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "https://my-oasis.org/api"
  maintainer_email: "vikrant.chaudhary@physik.hu-berlin.de"

logtransfer:
    enabled: true
    transfer_interval: 10

#logstash:
#  enable: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
