services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: true
  allowed_users:
      - vikrant.chaudhary@physik.hu-berlin.de
      - chaudhary@tmm.tu-darmstadt.de
north:
  jupyterhub_crypt_key: "65fd1f2aecd15e8f5fcf97fd54c004901b50ee67be1728bd5a31fb2d566d6b4f"
  tools:
    options:
      jupyter:
        image: ghcr.io/16-vikrant/nomad-oasis-tmm/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "https://my-oasis.org/api"
  maintainer_email: "vikrant.chaudhary@physik.hu-berlin.de"

logstash:
  enable: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
